name: simp_api
description: A simp and easy package to use REST Api in Flutter.
version: 0.0.1
authors:
  - Yazan Qtiesh
homepage: https://github.com/YazanQTT/simp_api

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
